spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flywaystudy
    username: localfly
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: "classpath:db/migration/{vendor}"
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/flywaystudy
    user: localfly
    password: admin
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace